# Generated by Django 4.2.7 on 2023-11-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15, verbose_name='이름')),
                ('nickname', models.CharField(max_length=20, unique=True, verbose_name='별명')),
                ('phone_number', models.CharField(max_length=11, null=True, verbose_name='전화번호')),
                ('address', models.CharField(max_length=50, null=True, verbose_name='주소')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
