# Generated by Django 4.2.7 on 2023-11-03 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obesity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('level', models.IntegerField(choices=[(1, '야윈 상태'), (3, '저체중'), (5, '이상적인 체중'), (7, '과체중'), (9, '비만')])),
                ('explanation', models.TextField(blank=True, verbose_name='설명')),
                ('pet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.pet', verbose_name='반려 동물')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
