# Generated by Django 4.2.7 on 2023-11-04 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_alter_pet_breed_alter_pet_gender'),
        ('obesity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obesity',
            name='pet_id',
        ),
        migrations.AlterField(
            model_name='obesity',
            name='explanation',
            field=models.TextField(verbose_name='비만도 설명'),
        ),
        migrations.CreateModel(
            name='ObesityHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('diagnosis_date', models.DateField(verbose_name='진단 일자')),
                ('explanation', models.TextField(blank=True, verbose_name='보호자 기록')),
                ('obesity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obesity.obesity', verbose_name='비만')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.pet', verbose_name='반려 동물')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
