# Generated by Django 4.2.7 on 2023-11-23 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obesity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obesityhistory',
            name='obesty_images',
            field=models.ImageField(blank=True, null=True, upload_to='obesity/', verbose_name='비만도 사진'),
        ),
    ]
