# Generated by Django 4.2.7 on 2023-11-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obesity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obesityhistory',
            name='explanation',
        ),
        migrations.RemoveField(
            model_name='obesityhistory',
            name='obesity',
        ),
        migrations.AddField(
            model_name='obesityhistory',
            name='breed',
            field=models.CharField(choices=[('Maltese', '말티즈'), ('Poodle', '푸들'), ('Bichon frise', '비숑 프리제'), ('Pomeranian', '포메라니안'), ('ETC', '기타')], default='기타', max_length=15, verbose_name='견종'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='obesityhistory',
            name='result',
            field=models.JSONField(default=dict, verbose_name='예측 결과'),
        ),
    ]
