# Generated by Django 4.2.7 on 2023-11-24 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obesity', '0002_obesityhistory_obesty_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obesityhistory',
            name='obesty_images',
            field=models.JSONField(blank=True, null=True, verbose_name='비만도 사진'),
        ),
    ]
