# Generated by Django 4.2.7 on 2023-11-24 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obesity', '0003_alter_obesityhistory_obesty_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obesityhistory',
            old_name='obesty_images',
            new_name='obesity_images',
        ),
    ]
