# Generated by Django 4.2.7 on 2023-12-05 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='이름')),
                ('breed', models.CharField(choices=[('Maltese', '말티즈'), ('Poodle', '푸들'), ('Bichon frise', '비숑 프리제'), ('Pomeranian', '포메라니안'), ('ETC', '기타')], max_length=20, verbose_name='견종')),
                ('gender', models.CharField(choices=[('Female', '암컷'), ('Male', '수컷'), ('Neutered/Spayed', '중성화')], max_length=20, verbose_name='성별')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='보호자')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
