# Generated by Django 4.2.7 on 2023-11-03 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('breed', models.CharField(choices=[('Retriever', '리트리버'), ('Pomeranian', '포메라니안'), ('Poodle', '푸들')], max_length=20)),
                ('gender', models.CharField(choices=[('Female', '암컷'), ('Male', '수컷'), ('Neutered/Spayed', '중성화')], max_length=20)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.owner', verbose_name='보호자')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
