# Generated by Django 4.2.7 on 2023-11-05 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='name',
            field=models.CharField(default='뭉치', max_length=20, verbose_name='이름'),
            preserve_default=False,
        ),
    ]
