# Generated by Django 4.2.7 on 2023-11-04 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_alter_pet_breed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(choices=[('Maltese', '말티즈'), ('Poodle', '푸들'), ('Bichon frise', '비숑 프리제'), ('Pomeranian', '포메라니안'), ('ETC', '기타')], max_length=20, verbose_name='견종'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('Female', '암컷'), ('Male', '수컷'), ('Neutered/Spayed', '중성화')], max_length=20, verbose_name='성별'),
        ),
    ]
