# Generated by Django 4.2.7 on 2023-11-05 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseasehistory',
            name='disease',
        ),
        migrations.RemoveField(
            model_name='diseasehistory',
            name='explanation',
        ),
        migrations.AddField(
            model_name='diseasehistory',
            name='result',
            field=models.JSONField(default=dict, verbose_name='예측 결과'),
        ),
        migrations.AlterField(
            model_name='diseasehistory',
            name='part',
            field=models.CharField(choices=[('Head', '머리'), ('Body', '몸통'), ('Leg', '다리'), ('Tail', '연접부')], max_length=10, verbose_name='질환 의심 부위'),
        ),
    ]
