# Generated by Django 4.2.7 on 2023-11-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseasehistory',
            name='disease_image',
            field=models.ImageField(blank=True, null=True, upload_to='disease_images/', verbose_name='질병 사진'),
        ),
    ]
