# Generated by Django 4.2.7 on 2023-11-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseasehistory',
            name='explanation',
            field=models.TextField(blank=True, verbose_name='보호자 기록'),
        ),
    ]
