# Generated by Django 4.2.7 on 2023-11-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0002_diseasehistory_disease_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasehistory',
            name='disease_image',
            field=models.ImageField(blank=True, null=True, upload_to='disease/', verbose_name='질병 사진'),
        ),
    ]
